apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-history-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-history-service
  template:
    metadata:
      labels:
        app: price-history-service
    spec:
      containers:
      - name: price-history-service
        image: price-history-service:latest
        imagePullPolicy: Never  # Add this line
        ports:
        - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: price-history-service
spec:
  selector:
    app: price-history-service
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP