apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-aggregator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-aggregator-service
  template:
    metadata:
      labels:
        app: shop-aggregator-service
    spec:
      containers:
      - name: shop-aggregator-service
        image: shop-aggregator-service:latest
        imagePullPolicy: Never  # Add this line
        ports:
        - containerPort: 3004
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shop-aggregator-service
spec:
  selector:
    app: shop-aggregator-service
  ports:
  - port: 80
    targetPort: 3004
  type: ClusterIP